### ISSUE TITLE
Does not build on GCC 4.9 on CentOS

### ISSUE THREAD

**Issue by adamnovak** [leahneukirchen/rs#1]
First I was missing some clock functions:

```
src/liboutils/getentropy_linux.o: In function `getentropy_fallback':
getentropy_linux.c:(.text+0x525): undefined reference to `clock_gettime'
```

After adding `-lrt` to the Makefile's lib flags, I am now missing a rule for some elliptic curve thing:

```
make: *** No rule to make target `src/usr.bin/signify/smult_curve25519_ref.o', needed by `src/usr.bin/signify/signify'.  Stop.
```

My Linux is:

```
Linux kolossus 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64 GNU/Linux
```

And my compiler:

```
gcc (GCC) 4.9.0
Copyright (C) 2014 Free Software Foundation, Inc.
```

All I wanted was to build `rs`...

**Comment by leahneukirchen** [comment]
Is this bug meant to be against outils?

Try `make src/usr.bin/rs/rs` and then use `src/usr.bin/rs/rs`.

**Comment by adamnovak** [comment]
Oh dear. Yes it is. Sorry!
